# Setup
title:               FanoCats
tagline:             (Toric) Fano Categories Database
description:         >- # this means to ignore newlines until "url:"
  A database of derived categories of smooth fano toric varieties.
url:                 https://mahrud.github.io
baseurl:             '/FanoCats' # the subpath of your site, e.g. /blog
cf_beacon:           '' # Cloudflare beacon token

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for entries
# collections:
#   varieties:
#     output: true

# Markdown specs
markdown: kramdown

kramdown:
  input: TeXdown
  # we use KaTeX
  math_engine: null
  # enable parsing Markdown inside html blocks
  parse_block_html: true
  # ↩ followed by a symbol to prevent emoji conversion
  footnote_backlink: "&#x21a9;&#xfe0e;"
  # don't make typographical conversions like >> to »
  gfm_quirks: [paragraph_end, no_auto_typographic]
  # disables syntax highlighter
  syntax_highlighter_opts:
    disable: "true"

# Exclusions from the final site
exclude:
  - TODO
  - README.md
  - LICENSE.md
  - proof.gemspec
  - Makefile
  - _cache

# Theme
remote_theme: "mahrud/proof"
